### ISSUE TITLE
Under which license is this code available?

### ISSUE THREAD

**Issue by mykaul** [Infinidat/infi.iscsiapi#1]
It's unclear (well, it seems to be missing).
https://pypi.hotlibs.com/infi.iscsiapi/package/0.2.3 seems to hint at PSF, but who knows.

**Comment by wiggin15** [comment]
Hi @mykaul. The package is licensed under the BSD (3-Clause) License. We'll update the classifiers in `setup.in` and add a `LICENSE` file.

**Comment by mykaul** [comment]
Excellent, thanks. Wish all other Infinidat repos were clear on their license.
https://www.theregister.co.uk/2017/05/15/infinidat_benchmark_test/ was not very clear on this:
"... found on our GitHub page is from one of our many (30) open-source projects on GitHub "

**Comment by wiggin15** [comment]
Specifically, the slimfastq repository mentioned in the article is unmaintained.
We updated many of the other Python repositories (maybe still not all) following your feedback. Thanks.
