### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by PrudhviKrish** [Infinidat/infi.iscsiapi#2]
Hi,

I have observed that it has a dependency of infi.wmi.
It has been used in windows.py in line number 6.

Can you please resolve this dependency issue?

Thanks,
Prudhvi

**Comment by wiggin15** [comment]
Hi. The dependency on infi.wmi should not be an issue, if you use `infi.iscsiapi.get_iscsiapi` (see the readme for an example). The import to `windows.py` should only happen on Windows systems.
If the dependency on infi.wmi is a problem, please explain why.

**Comment by PrudhviKrish** [comment]
Hi,

Sorry for the delay, I am using this for both Windows and Linux. For Linux, it is working properly but for Windows, it is throwing dependency issue.

Thanks,
Prudhvi

**Comment by wiggin15** [comment]
I can't help you without more information. What exactly is it throwing? Do you have infi.wmi (and the rest of the dependencies) installed? Please paste an output with the problem. This is working properly in our environment.

**Comment by PrudhviKrish** [comment]
Hi,

If we are installing "infi.iscsiapi" using "pip install infi.iscsiapi" its good practice to install all the dependency packages what we are using in the code but here it is not installing "infi.wmi". If I try to execute my code after installing only "infi.iscsiapi" it is failing with following error message:

**C:\Python34\lib\site-packages\infi\iscsiapi\__init__.py:8: in get_iscsiapi
    __iscsiapi = _get_platform_specific_iscsiapi()
C:\Python34\lib\site-packages\infi\iscsiapi\__init__.py:23: in _get_platform_specific_iscsiapi
    from . import windows
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    from infi.win32service import ServiceControlManagerContext
    from infi.execute import execute_assert_success, execute, ExecutionError
    from . import base
    from . import auth as iscsiapi_auth
    from infi.dtypes.iqn import IQN
>   from infi.wmi import WmiClient
E   ImportError: No module named 'infi.wmi'

C:\Python34\lib\site-packages\infi\iscsiapi\windows.py:6: ImportError**

"infi.iscsiapi" logs:
~\Documents\GitHub> pip install infi.iscsiapi
Collecting infi.iscsiapi
  Using cached infi.iscsiapi-0.2.9.tar.gz
Collecting infi.dtypes.iqn (from infi.iscsiapi)
  Using cached infi.dtypes.iqn-0.4.0.tar.gz
Collecting infi.execute (from infi.iscsiapi)
  Using cached infi.execute-0.1.7.tar.gz
Collecting infi.os_info (from infi.iscsiapi)
  Using cached infi.os_info-0.1.9.tar.gz
Collecting infi.pkgmgr (from infi.iscsiapi)
  Using cached infi.pkgmgr-0.1.15.tar.gz
Collecting infi.win32service (from infi.iscsiapi)
  Using cached infi.win32service-0.1.8.tar.gz
Requirement already satisfied: setuptools in c:\python34\lib\site-packages (from infi.iscsiap
Collecting infi.monotonic_time (from infi.execute->infi.iscsiapi)
  Using cached infi.monotonic_time-0.1.8-py3-none-any.whl
Requirement already satisfied: git-py in c:\python34\lib\site-packages (from infi.os_info->in
Collecting infi.pyutils (from infi.pkgmgr->infi.iscsiapi)
  Using cached infi.pyutils-1.1.3.tar.gz
Collecting infi.run_as_root (from infi.pkgmgr->infi.iscsiapi)
  Using cached infi.run_as_root-0.1.7.tar.gz
Requirement already satisfied: munch in c:\python34\lib\site-packages (from infi.pkgmgr->infi
Requirement already satisfied: six in c:\python34\lib\site-packages (from git-py->infi.os_inf
Requirement already satisfied: mock in c:\python34\lib\site-packages (from infi.pyutils->infi
Requirement already satisfied: emport in c:\python34\lib\site-packages (from infi.pyutils->in
Requirement already satisfied: packaging in c:\python34\lib\site-packages (from infi.pyutils-
Requirement already satisfied: pbr>=0.11 in c:\python34\lib\site-packages (from mock->infi.py
Requirement already satisfied: Logbook>=0.11.0 in c:\python34\lib\site-packages (from emport-
Requirement already satisfied: pyparsing>=2.0.2 in c:\python34\lib\site-packages (from packag
Installing collected packages: infi.dtypes.iqn, infi.monotonic-time, infi.execute, infi.os-in

  Running setup.py install for infi.dtypes.iqn ... done
  Running setup.py install for infi.execute ... done
  Running setup.py install for infi.os-info ... done
  Running setup.py install for infi.pyutils ... done
  Running setup.py install for infi.run-as-root ... done
  Running setup.py install for infi.pkgmgr ... done
  Running setup.py install for infi.win32service ... done
  Running setup.py install for infi.iscsiapi ... done
Successfully installed infi.dtypes.iqn-0.4.0 infi.execute-0.1.7 infi.iscsiapi-0.2.9 infi.mono
n-as-root-0.1.7 infi.win32service-0.1.8

Thanks,
Prudhvi

**Comment by wiggin15** [comment]
I see. We are missing "infi.wmi" from our "install_requires" dependencies. We will fix this. In the meantime you can work around this by manually installing infi.wmi using pip. Thanks.
