### ISSUE TITLE
windows-xp get_sessions_of_target not work

### ISSUE THREAD

**Issue by lizhenfeiok** [Infinidat/infi.iscsiapi#3]

**Comment by wiggin15** [comment]
Hi @lizhenfeiok . Windows XP (and Windows Server 2003) and older are not supported by infi.iscsiapi.

**Comment by lizhenfeiok** [comment]
I test that "results = self._client.ExecQuery(query)" has results but "results.ItemIndex(index)" doesn't work. Does not "ItemIndex" function support windows XP?

**Comment by wiggin15** [comment]
Since I don't have Windows XP available, it is not supported and I'm afraid I can't help with that.

**Comment by lizhenfeiok** [comment]
Thanks anyway. Good luck ！
